# Generated by Django 4.1 on 2022-09-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_logmessage_email_logmessage_name_logmessage_severity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmessage',
            name='severity',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], null=True),
        ),
    ]
