# Generated by Django 4.1 on 2022-09-07 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_logmessage_email_alter_logmessage_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Text Message Application'), (2, 'Email Message Application'), (3, 'Benefit System Application'), (4, 'Backend System Application'), (5, 'Frontend System Aplication')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='logmessage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='logmessage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='logmessage',
            name='subject',
        ),
        migrations.AddField(
            model_name='logmessage',
            name='appname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.application'),
        ),
        migrations.AddField(
            model_name='logmessage',
            name='users',
            field=models.ManyToManyField(blank=True, to='hello.users'),
        ),
    ]
