# Generated by Django 4.1 on 2022-09-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_application_users_remove_logmessage_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmessage',
            name='users',
        ),
        migrations.AddField(
            model_name='logmessage',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logmessage',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
