# Generated by Django 4.1 on 2022-09-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_remove_logmessage_users_logmessage_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
