# Generated by Django 4.1 on 2022-09-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_alter_application_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logmessage',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
