# Generated by Django 4.1 on 2022-09-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_logmessage_subject_alter_logmessage_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='appname',
        ),
        migrations.RemoveField(
            model_name='logmessage',
            name='name',
        ),
    ]
