# Generated by Django 4.1 on 2022-09-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_logmessage_assign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logmessage',
            old_name='appname',
            new_name='applicationname',
        ),
        migrations.RemoveField(
            model_name='application',
            name='appname',
        ),
        migrations.AddField(
            model_name='application',
            name='applicationname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='contactemail',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
